【Realtime Database更新処理】20200508
Naoya-Hayashi/portfolio-admin pull request #6
Opened 2020-05-08 10:35 UTC by Naoya-Hayashi

# レビュー観点
realtime databaseとsequel proの連携しました。
開発用portfolioでrealtime databaseのグラフを表示しました。
 
# 変更内容／作業内容
 - [ ] mySQLからデータを取得
 - [ ] SDKの初期化
 - [ ] データを形成
 - [ ] グラフへ反映

<img width="926" alt="スクリーンショット 2020-05-08 19 33 52" src="https://user-images.githubusercontent.com/62989057/81397810-0206a080-9163-11ea-88b8-3550c3ccaf6a.png">

2020-05-08 17:54 UTC, hidekishibashi requested changes
確認してからPR出すようにしてください

2020-05-08 17:54 UTC, hidekishibashi commented on .project
> +	<natures>cd
```suggestion
	<natures>
```
これは？

2020-05-08 17:54 UTC, hidekishibashi commented on src/main/java/com/seattleacademy/team20/SkillController.java
> +   * Simply selects the home view to render by returning its name. * @throuws
```suggestion
   * Simply selects the home view to render by returning its name. *
```

2020-05-08 17:54 UTC, hidekishibashi commented on src/main/java/com/seattleacademy/team20/SkillController.java
> +   * IOException
```suggestion
   * @throuws IOException
```

2020-05-08 17:54 UTC, hidekishibashi commented on src/main/java/com/seattleacademy/team20/SkillController.java
> +    Map<String, List<Skills>> skillMap = skills.stream().collect(Collectors.groupingBy(Skills::getSkillId));
getSkillId
これでgroupingByして意味ある？

2020-05-08 17:56 UTC, hidekishibashi commented
次回PRの際は、以下の動画を証跡として共有してください。
・更新前のデータベースの情報
・更新中のサーバ起動や画面挙動
・更新後のデータベースの情報

2020-05-08 17:58 UTC, hidekishibashi commented
勘違いだったら申し訳ないですが、ソース見た感じ全然できてない感じするので上記の証跡をお願いしますー

2020-05-11 01:59 UTC, Naoya-Hayashi commented on src/main/java/com/seattleacademy/team20/SkillController.java
> +    Map<String, List<Skills>> skillMap = skills.stream().collect(Collectors.groupingBy(Skills::getSkillId));
getSkillCategoryに修正しました。

2020-05-11 06:34 UTC, hidekishibashi requested changes

2020-05-11 06:34 UTC, hidekishibashi commented on src/main/java/com/seattleacademy/team20/SkillController.java
> +    List<Map<String, Object>> DataList = new ArrayList<Map<String, Object>>();
```suggestion
    List<Map<String, Object>> dataList = new ArrayList<Map<String, Object>>();
```

2020-05-11 06:34 UTC, hidekishibashi commented on src/main/java/com/seattleacademy/team20/SkillController.java
> +      ref.setValue(DataList, new DatabaseReference.CompletionListener() {
このrealtime databaseへのアップロードがfor文の中で行われており、
無駄にアクセス＆アップロードされてしまっています。

2020-05-11 06:37 UTC, hidekishibashi commented on src/main/java/com/seattleacademy/team20/SkillController.java
> +    List<Map<String, Object>> DataList = new ArrayList<Map<String, Object>>();
Javaではキャメルケースで変数名を定義します

2020-05-11 06:39 UTC, hidekishibashi commented on src/main/java/com/seattleacademy/team20/SkillController.java
> +      ref.setValue(DataList, new DatabaseReference.CompletionListener() {
証跡動画からもわかりますが、
「Data save successfully.」
このアップロード完了メッセージが3回出力されています。

2020-05-11 07:49 UTC, Naoya-Hayashi commented on src/main/java/com/seattleacademy/team20/SkillController.java
> +    List<Map<String, Object>> DataList = new ArrayList<Map<String, Object>>();
キャメルケースの書き方、勉強しておきます。

2020-05-11 07:52 UTC, Naoya-Hayashi commented on src/main/java/com/seattleacademy/team20/SkillController.java
> +      ref.setValue(DataList, new DatabaseReference.CompletionListener() {
for文後に閉じカッコを入れ、1回の出力に設定しました。

2020-05-11 08:25 UTC, hidekishibashi approved these changes

2020-05-11 08:25 UTC, merged